spring:
  application:
    name: example-three
server:
  port: 8083
mybatis:
  #\u5B9E\u4F53\u7C7B
  type-aliases-package: com.gfyw.example.bean
management:
  endpoints:
    web:
      exposure:
        #\u66B4\u9732\u7AEF\u70B9
        include: bus-refresh
