spring:
  application:
    name: client-one
server:
  port: 8091
feign:
  hystrix:
    enabled: true
# 放开所有端点,显示详细信息让admin监听
management:
  endpoints:
    web:
      exposure:
        #\u66B4\u9732\u7AEF\u70B9
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
        