spring:
  application:
    name: client-one
  # 链路追踪
  sleuth:
   web:
    client:
     enabled: true
    sampler:
     probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
server:
  port: 8091
feign:
  hystrix:
    enabled: true
# 放开所有端点,显示详细信息让admin监听
management:
  endpoints:
    web:
      exposure:
        #\u66B4\u9732\u7AEF\u70B9
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
        