spring:
  application:
    name: client-two
server:
  port: 8092
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        #\u66B4\u9732\u7AEF\u70B9
        include: hystrix.stream,bus-refresh